# Generated by Django 4.0.8 on 2023-09-26 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
