# Generated by Django 4.2.5 on 2023-10-26 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('cnpj_empresa', models.CharField(max_length=50, verbose_name='CNPJ Empresa')),
                ('nome_empresa', models.CharField(max_length=255, verbose_name='Nome Empresa')),
                ('email_empresa', models.EmailField(max_length=100, unique=True, verbose_name='E-mail')),
                ('categoria_empresa', models.CharField(choices=[('TECNOLOGIA', 'Tecnologia'), ('AGRO', 'Agro Negócio')], max_length=50, verbose_name='Categoria Empresa')),
                ('quitado', models.BooleanField(default=False, verbose_name='Quitado')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
